#	@(#)Makefile	8.3 (Berkeley) 3/27/94
# $FreeBSD: src/sbin/mount_ext2fs/Makefile,v 1.3.6.1 2001/04/25 10:58:34 ru Exp $

PROG=	mount_tarfs
MAN=	mount_tarfs.8

LDADD=	-lutil
DPADD=	${LIBUTIL}

.include <bsd.prog.mk>
